### ISSUE TITLE
Is this library expected to work against libsnark master?

### ISSUE THREAD

**Issue by copumpkin** [gstew5/snarkl#11]
I've been packaging snarkl for nixpkgs and am running it against libsnark master, and a lot of the tests (but not all) seem to fail for reasons I don't understand.

For example, in the first test (`if-then-else`):

```
Generating Keys
(enter) Call to r1cs_ppzksnark_generator   	[             ]	(1133431.1352s x1339.09 from start)
  (enter) Call to r1cs_constraint_system::swap_AB_if_beneficial	[             ]	(1133431.1359s x1339.09 from start)
    (enter) Estimate densities                 	[             ]	(1133431.1360s x1339.09 from start)
      * Non-zero A-count (estimate): 7
      * Non-zero B-count (estimate): 9
    (leave) Estimate densities                 	[0.0000s x1.25]	(1133431.1360s x1339.09 from start)
    (enter) Perform the swap                   	[             ]	(1133431.1360s x1339.09 from start)
    (leave) Perform the swap                   	[0.0000s x1.02]	(1133431.1360s x1339.09 from start)
  (leave) Call to r1cs_constraint_system::swap_AB_if_beneficial	[0.0001s x0.93]	(1133431.1360s x1339.09 from start)
  (enter) Call to r1cs_to_qap_instance_map_with_evaluation	[             ]	(1133431.1361s x1339.09 from start)
Key-generation Failed!
```

I can't tell what actually went wrong with that invocation, but all the failures look like that. They enter `r1cs_to_qap_instance_map_with_evaluation` but never leave it. Given that there are other blocks entered fairly early in that function, it seems like there's a small number of places that could be failing, but I haven't looked more carefully.

Here's the full list of passes and fails:

```
Field Tests
  if-then-else
    1-1 FAILED [1]
  bigsum
    2-1 FAILED [2]
    2-2 FAILED [3]
    2-3 FAILED [4]
    2-4 FAILED [5]
  arrays
    3-1
    3-2
    3-3
    3-4
    4-1
    4-2
    4-3
    4-4
    5-1 FAILED [6]
    5-2 FAILED [7]
    5-3 FAILED [8]
    5-4 FAILED [9]
  times
    6-1 FAILED [10]
  forall
    7-1
  forall2
    8-1
  unused inputs
    11-1
  multiplicative identity
    13-1 FAILED [11]
  opt: 0x * 3y = out ~~> out=0
    14-1
  exp_binop smart constructor: 3 - (2 - 1) = 2
    15-1
  lists
    26-1
    27-1
    28-1
    29-1 FAILED [12]
    30-1
    37-1 FAILED [13]
  div
    31-1
    31-1
    31-1
    31-1
  beta
    34-1 FAILED [14]
  trees
    35-1
Boolean Tests
  and
    9-1 FAILED [15]
    9-2 FAILED [16]
    9-3 FAILED [17]
    9-4 FAILED [18]
  xor
    10-1 FAILED [19]
    10-2 FAILED [20]
    10-3 FAILED [21]
    10-4 FAILED [22]
  boolean eq
    12-1 FAILED [23]
    12-2 FAILED [24]
    12-3 FAILED [25]
    12-4 FAILED [26]
  bool inputs
    16-1 FAILED [27]
  array
    17-1
  input array
    18-1 FAILED [28]
  products
    19-1 FAILED [29]
    20-1 FAILED [30]
    21-1 FAILED [31]
  products
    22-1 FAILED [32]
    23-1 FAILED [33]
  peano
    24-1
  lam
    25-1
  zeq
    32-1 FAILED [34]
    32-2 FAILED [35]
    32-3 FAILED [36]
  eq
    33-1
    33-2
    33-3
    33-3
    33-3
    33-3
  sum
    36-1 FAILED [37]
    36-2 FAILED [38]
Keccak Tests
  keccak
    keccak-2 FAILED [39]
    keccak-2 FAILED [40]
```

It's unclear to me whether it's an issue with my packaging or whether stuff has just changed in `libsnark` in the couple of years since the @jkroll fork `snarkl` is using.

cc @gstew5

**Comment by copumpkin** [comment]
Ah, my issue seems to be:

```
(enter) Call to r1cs_ppzksnark_generator   	[             ]	(1147911.6906s x1322.21 from start)
  (enter) Call to r1cs_constraint_system::swap_AB_if_beneficial	[             ]	(1147911.6907s x1322.21 from start)
    (enter) Estimate densities                 	[             ]	(1147911.6907s x1322.21 from start)
      * Non-zero A-count (estimate): 3
      * Non-zero B-count (estimate): 6
    (leave) Estimate densities                 	[0.0000s x1.06]	(1147911.6908s x1322.21 from start)
    (enter) Perform the swap                   	[             ]	(1147911.6908s x1322.21 from start)
    (leave) Perform the swap                   	[0.0000s x1.06]	(1147911.6908s x1322.21 from start)
  (leave) Call to r1cs_constraint_system::swap_AB_if_beneficial	[0.0001s x0.94]	(1147911.6908s x1322.21 from start)
  (enter) Call to r1cs_to_qap_instance_map_with_evaluation	[             ]	(1147911.6910s x1322.21 from start)
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: libff::get_root_of_unity: expected n == (1u << logn)
```

Note that the error at the end was getting lost in the logs I pasted earlier.

**Comment by copumpkin** [comment]
Turns out that we're asking `libff` for a root of unity for something that isn't a power of 2:

https://github.com/scipr-lab/libff/blob/7b19ed91edb61a21418b62b3890c74b2ac57668e/libff/algebra/fields/field_utils.tcc#L40-L46

Where `n = 6`, in the case of this test:

```haskell
-- | 32. zeq test
bool_prog32
  = do { x <- fresh_input
       ; return $ zeq x
       }
```

**Comment by copumpkin** [comment]
I'm now confused because it seems to be failing here:

https://github.com/scipr-lab/libfqfft/blob/56f33607a1b6e552be685d1359f053dab39f90b7/libfqfft/evaluation_domain/get_evaluation_domain.tcc#L33-L43

so it's throwing an exception with a `catch` but I'm seeing it bubble up and cause a failure.

**Comment by copumpkin** [comment]
For anyone following along, I'm trying to see if this is a compiler bug (and if so produce a minimal repro), since it seems unusual that I'd be getting exceptions that should be caught by a `catch(...)` block. I'll update here if it ends up being something weird with snarkl, and close in the meantime.

**Comment by gstew5** [comment]
I've been quite delinquent keeping up with the issues you've raised -- many apologies!

As you point out above, we've tested Snarkl only against the fork of libsnark at https://github.com/jkroll/libsnark, which is about 200 commits behind master. Unfortunately, I don't have the bandwidth at the moment to bring the compiler back up to date (currently working on other research projects). But I'd be more than happy to merge a pull request if you'd like to put one together :-) 

In the end, did you manage to determine whether the root-of-unity issue above was indeed a compiler error, and if so, did you find a minimal example that reproduces it?
