### ISSUE TITLE
starkl?

### ISSUE THREAD

**Issue by copumpkin** [gstew5/snarkl#9]
With the release of the new ZK-STARK paper, it might be interesting to see how snarkl needs to change to accommodate it: https://eprint.iacr.org/2018/046.pdf

**Comment by gstew5** [comment]
Many thanks for the pointer. Snarkl should port relatively easily to any crypto backend that uses Rank-1 Constraint Systems (R1CS) to encode arithmetized programs. However, ZK-STARK's arithmetization scheme, as described in Section 2 of the paper you cite above, uses a different representation (AIR, for algebraic intermediate representation). It's not clear to me yet exactly what would have to change to generate code in that representation.
